aliases:
  - &filter-only-master
    branches:
      only:
        - master

image-defaults: &image-defaults
  docker:
    - image: circleci/node:8.11-stretch

version: 2
jobs:
  build:
    working_directory: ~/repo
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:  .
      - run:
          name: install dependencies
          command: |
            npm install
      - run:
          name: run test
          command: |
            npm test

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build:
        filters: *filter-only-master
