aliases:
  - &filter-only-master
    branches:
      only:
        - 3-include-pipeline

version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      - heroku/test:
          filters: *filter-only-master
      - heroku/deploy-via-git:
          filters: *filter-only-master