version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  deploy:
    steps:
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  heroku_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master # only run deploy-via-git job on master branch