version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  deploy:
    - heroku/deploy-via-git:
        filters:
          branches:
            only: master

  build:
    steps:
      - run:
          name: Running unit tests
          command: |
            npm test

workflows:
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            -build