version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  build:
    steps:
      - run:
          name: Running unit tests
          command: |
            npm test

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          filters:
            branches:
              only: master
          requires:
            -build