version: 2.1

aliases:
  - &filter-only-master
    branches:
      only:
        - 3-include-pipeline

attach-workspace: &attach-workspace
  attach_workspace:
    at: ~/repo

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    machine: true
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: run test
          command: |
            npm test

  workflows:
    version: 2.1
    build-and-test:
      jobs:
        - test:
            filters: *filter-only-master
