version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
attach-workspace: &attach-workspace
  attach_workspace:
    at: ~/repo
jobs:
  build-and-install-dependencies:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-repo-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies with NPM
          command: npm install # replace with `yarn install` if using yarn
      - save_cache: # special step to save the dependency cache
          key: v1-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
  unit-test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: npm test --passWithNoTests # replace with `yarn test` if using yarn
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
  package-application:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Package Application
          command: |
            npm install
            yarn run build --yes
            mkdir -p /tmp/app
            cp -avR build/* /tmp/app
            cp .circleci/server.js /tmp/app
            cp .circleci/package.json /tmp/app
      - store_artifacts:
          path: /tmp/app
  deploy-staging:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku Staging
          command: |
            cd /tmp/app
            git config --global user.name "CircleCI"
            git init
            git add .
            git commit -m "Deploy"
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGING.git master -f
  deploy-production:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku Production
          command: |
            cd /tmp/app
            git config --global user.name "CircleCI"
            git init
            git add .
            git commit -m "Deploy"
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master -f

workflows:
  Build and Test:
    jobs:
      - build-and-install-dependencies
      - package-application:
          requires:
            - build-and-install-dependencies
      - deploy-staging:
          requires:
            - package-application
      - approve-deploy-to-production:
          type: approval
          requires:
            - deploy-staging
      - deploy-production:
          requires:
            - approve-deploy-to-production
