version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1


workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
        filters:
          branches:
            only: master
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master